//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int id { get; set; }
        public string author { get; set; }
        public string title { get; set; }
        public Nullable<int> number_of_pages { get; set; }
        public string genre { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual user user { get; set; }
    }
}
